core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf.urls.static import static                      # used for static files

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),

    path('', include('homepage.urls')),
    path('inventory/', include('inventory.urls')),
    path('transactions/', include('transactions.urls')),
]

transactions/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
    path('suppliers/', views.SupplierListView.as_view(), name='suppliers-list'),
    path('suppliers/new', views.SupplierCreateView.as_view(), name='new-supplier'),
    path('suppliers/<pk>/edit', views.SupplierUpdateView.as_view(), name='edit-supplier'),
    path('suppliers/<pk>/delete', views.SupplierDeleteView.as_view(), name='delete-supplier'),
    path('suppliers/<name>', views.SupplierView.as_view(), name='supplier'),

    path('purchases/', views.PurchaseView.as_view(), name='purchases-list'), 
    path('purchases/new/', views.SelectSupplierView.as_view(), name='select-supplier'),
    path('purchases/new/<int:pk>/', views.PurchaseCreateView.as_view(), name='new-purchase'),
    path('purchases/<pk>/delete/', views.PurchaseDeleteView.as_view(), name='delete-purchase'),

    path('sales/', views.SaleView.as_view(), name='sales-list'),
    path('sales/new/', views.SelectCostumerView.as_view(), name='select-costumer'),
    path('sales/new/<int:pk>/', views.SaleCreateView.as_view(), name='new-sale'),
    path('sale/<pk>/delete/', views.SaleDeleteView.as_view(), name='delete-sale'),


    path("purchases/<billno>", views.PurchaseBillView.as_view(), name="purchase-bill"),
    path("sales/<billno>", views.SaleBillView.as_view(), name="sale-bill"),

    path('agents/', views.AgentListView.as_view(), name='agent-list'),
    path('agents/new', views.AgentCreateView.as_view(), name='new-agent'),
    path('agents/<pk>/edit', views.AgentUpdateView.as_view(), name='edit-agents'),
    path('agents/<pk>/delete', views.AgentDeleteView.as_view(), name='delete-agents'),
    path('agents/<name>', views.AgentView.as_view(), name='agents'),


    path('costumer/', views.CostumerListView.as_view(), name='costumer-list'),
    path('costumer/new', views.CostumerCreateView.as_view(), name='new-costumer'),
    path('costumer/<pk>/edit', views.CostumerUpdateView.as_view(), name='edit-costumer'),
    path('costumer/<pk>/delete', views.CostumerDeleteView.as_view(), name='delete-costumer'),
    path('costumer/<name>', views.CostumerView.as_view(), name='costumer'),
]

transactions/models.py
from django.db import models
from inventory.models import Stock


# contains suppliers
class Supplier( models.Model ):
    id = models.AutoField( primary_key=True )
    name = models.CharField( max_length=25 )
    phone = models.CharField( max_length=12, unique=True )
    address = models.CharField( max_length=200 )
    email = models.EmailField( max_length=254, unique=True )
    nipt = models.CharField( max_length=10, unique=True )
    is_deleted = models.BooleanField( default=False )

    def __str__(self):
        return self.name


class Agent( models.Model ):
    id = models.AutoField( primary_key=True )
    name = models.CharField( max_length=150 )
    phone = models.CharField( max_length=12, unique=True )
    is_deleted = models.BooleanField( default=False )

    def __str__(self):
        return self.name


class Costumer( models.Model ):
    id = models.AutoField( primary_key=True )
    name = models.CharField( max_length=150 )
    phone = models.CharField( max_length=12, unique=True )
    address = models.CharField( max_length=200 )
    email = models.EmailField( max_length=254, unique=True )
    nipt = models.CharField( max_length=10, unique=True )
    agent = models.ForeignKey( Agent, on_delete=models.CASCADE, related_name='costumeragent' )
    is_deleted = models.BooleanField( default=False )

    def __str__(self):
        return self.name


# contains the purchase bills made
class PurchaseBill( models.Model ):
    billno = models.AutoField( primary_key=True )
    time = models.DateTimeField( auto_now=True )

    supplier = models.ForeignKey( Supplier, on_delete=models.CASCADE, related_name='purchasesupplier' )

    def __str__(self):
        return "Bill no: " + str( self.billno )

    def get_items_list(self):
        return PurchaseItem.objects.filter( billno=self )

    def get_total_price(self):
        purchaseitems = PurchaseItem.objects.filter( billno=self )
        total = 0
        for item in purchaseitems:
            total += item.totalprice
        return total


# contains the purchase stocks made
class PurchaseItem( models.Model ):
    billno = models.ForeignKey( PurchaseBill, on_delete=models.CASCADE, related_name='purchasebillno' )
    stock = models.ForeignKey( Stock, on_delete=models.CASCADE, related_name='purchaseitem' )
    quantity = models.IntegerField( default=1 )
    perprice = models.IntegerField( default=1 )
    totalprice = models.IntegerField( default=1 )

    def __str__(self):
        return "Bill no: " + str( self.billno.billno ) + ", Item = " + self.stock.name


# contains the other details in the purchases bill
class PurchaseBillDetails( models.Model ):
    billno = models.ForeignKey( PurchaseBill, on_delete=models.CASCADE, related_name='purchasedetailsbillno' )
    total = models.CharField( max_length=50, blank=True, null=True )
    supplier = models.ForeignKey( Supplier, on_delete=models.CASCADE, related_name='purchasedetailsupplier' )

    def __str__(self):
        return "Bill no: " + str( self.billno.billno )


# contains the sale bills made
class SaleBill( models.Model ):
    billno = models.AutoField( primary_key=True )
    time = models.DateTimeField( auto_now=True )
    costumer = models.ForeignKey( Costumer, on_delete=models.CASCADE, related_name='salecostumer' )
    agent = models.ForeignKey( Agent, on_delete=models.CASCADE, related_name='saleagent' )

    def __str__(self):
        return "Bill no: " + str( self.billno )

    def get_items_list(self):
        return SaleItem.objects.filter( billno=self )

    def get_total_price(self):
        saleitems = SaleItem.objects.filter( billno=self )
        total = 0
        for item in saleitems:
            total += item.totalprice
        return total


# contains the sale stocks made
class SaleItem( models.Model ):
    billno = models.ForeignKey( SaleBill, on_delete=models.CASCADE, related_name='salebillno' )
    stock = models.ForeignKey( Stock, on_delete=models.CASCADE, related_name='saleitem' )
    quantity = models.IntegerField( default=1 )
    perprice = models.IntegerField( default=1 )
    totalprice = models.IntegerField( default=1 )

    def __str__(self):
        return "Bill no: " + str( self.billno.billno ) + ", Item = " + self.stock.name


# contains the other details in the sales bill
class SaleBillDetails( models.Model ):
    billno = models.ForeignKey( SaleBill, on_delete=models.CASCADE, related_name='saledetailsbillno' )
    total = models.CharField( max_length=50, blank=True, null=True )
    costumer = models.ForeignKey( Costumer, on_delete=models.CASCADE, related_name='costumersale' )
    agent = models.ForeignKey( Agent, on_delete=models.CASCADE, related_name='agentsale' )

    def __str__(self):
        return "Bill no: " + str( self.billno.billno )

transactions/views.py
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import (
    View,
    ListView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import (
    PurchaseBill,
    Supplier,
    PurchaseItem,
    PurchaseBillDetails,
    SaleBill,
    SaleItem,
    SaleBillDetails,
    Costumer,
    Agent

)
from .forms import (
    SelectSupplierForm,
    PurchaseItemFormset,
    PurchaseDetailsForm,
    SupplierForm,
    SaleForm,
    SaleItemFormset,
    SaleDetailsForm,
    AgentForm,
    CostumerForm,
    # SelectAgentForm,
    # SelectCostumerForm,
    SelectCostumerForm
)
from inventory.models import Stock


class SupplierListView( ListView ):
    model = Supplier
    template_name = "suppliers/suppliers_list.html"
    queryset = Supplier.objects.filter( is_deleted=False )
    paginate_by = 10


# used to add a new supplier
class SupplierCreateView( SuccessMessageMixin, CreateView ):
    model = Supplier
    form_class = SupplierForm
    success_url = '/transactions/suppliers'
    success_message = "Supplier has been created successfully"
    template_name = "suppliers/edit_supplier.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data( **kwargs )
        context["title"] = 'New Supplier'
        context["savebtn"] = 'Add Supplier'
        return context

    # used to update a supplier's info


class SupplierUpdateView( SuccessMessageMixin, UpdateView ):
    model = Supplier
    form_class = SupplierForm
    success_url = '/transactions/suppliers'
    success_message = "Supplier details has been updated successfully"
    template_name = "suppliers/edit_supplier.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data( **kwargs )
        context["title"] = 'Edit Supplier'
        context["savebtn"] = 'Save Changes'
        context["delbtn"] = 'Delete Supplier'
        return context


# used to delete a supplier
class SupplierDeleteView( View ):
    template_name = "suppliers/delete_supplier.html"
    success_message = "Supplier has been deleted successfully"

    def get(self, request, pk):
        supplier = get_object_or_404( Supplier, pk=pk )
        return render( request, self.template_name, {'object': supplier} )

    def post(self, request, pk):
        supplier = get_object_or_404( Supplier, pk=pk )
        supplier.is_deleted = True
        supplier.save()
        messages.success( request, self.success_message )
        return redirect( 'suppliers-list' )


# used to view a supplier's profile
class SupplierView( View ):
    def get(self, request, name):
        supplierobj = get_object_or_404( Supplier, name=name )
        bill_list = PurchaseBill.objects.filter( supplier=supplierobj )
        page = request.GET.get( 'page', 1 )
        paginator = Paginator( bill_list, 10 )
        try:
            bills = paginator.page( page )
        except PageNotAnInteger:
            bills = paginator.page( 1 )
        except EmptyPage:
            bills = paginator.page( paginator.num_pages )
        context = {
            'supplier': supplierobj,
            'bills': bills
        }
        return render( request, 'suppliers/supplier.html', context )


class CostumerListView( ListView ):
    model = Costumer
    template_name = "costumer/costumer_list.html"
    queryset = Costumer.objects.filter( is_deleted=False, )
    paginate_by = 10


class CostumerCreateView( SuccessMessageMixin, CreateView ):
    model = Costumer
    form_class = CostumerForm
    success_url = '/transactions/costumer'
    success_message = "Costumer has been created successfully"
    template_name = "costumer/edit_costumer.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data( **kwargs, )
        context["title"] = 'New Costumer'
        context["savebtn"] = 'Add Costumer'
        return context


# used to update a supplier's info
class CostumerUpdateView( SuccessMessageMixin, UpdateView ):
    model = Costumer
    form_class = CostumerForm
    success_url = '/transactions/costumer'
    success_message = "Costumer details has been updated successfully"
    template_name = "costumer/edit_costumer.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data( **kwargs, )
        context["title"] = 'Edit Costumer'
        context["savebtn"] = 'Save Changes'
        context["delbtn"] = 'Delete Costumer'
        return context


# used to delete a supplier
class CostumerDeleteView( View ):
    template_name = "costumer/delete_costumer.html"
    success_message = "Costumer has been deleted successfully"

    def get(self, request, pk):
        costumer = get_object_or_404( Costumer, pk=pk )
        return render( request, self.template_name, {'object': costumer} )

    def post(self, request, pk):
        costumer = get_object_or_404( Costumer, pk=pk )
        costumer.is_deleted = True
        costumer.save()
        messages.success( request, self.success_message )
        return redirect( 'costumer-list' )


# used to view a supplier's profile
class CostumerView( View ):
    def get(self, request, name):
        costumerobj = get_object_or_404( Costumer, name=name )
        sale_bill = SaleBill.objects.filter( costumer=costumerobj )
        page = request.GET.get( 'page', 1 )
        paginator = Paginator( sale_bill, 10 )
        try:
            sales = paginator.page( page )
        except PageNotAnInteger:
            sales = paginator.page( 1 )
        except EmptyPage:
            sales = paginator.page( paginator.num_pages )
        context = {
            'costumer': costumerobj,
            'bills': sales
        }
        return render( request, 'costumer/costumer.html', context )


# shows the list of bills of all purchases
class PurchaseView( ListView ):
    model = PurchaseBill
    template_name = "purchases/purchases_list.html"
    context_object_name = 'bills'
    ordering = ['-time']
    paginate_by = 10


class AgentListView( ListView ):
    model = Agent
    template_name = "agents/agents_list.html"
    queryset = Agent.objects.filter( is_deleted=False )
    paginate_by = 10


# used to add a new supplier
class AgentCreateView( SuccessMessageMixin, CreateView ):
    model = Agent
    form_class = AgentForm
    success_url = '/transactions/agents'
    success_message = "Agent has been created successfully"
    template_name = "agents/edit_agents.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data( **kwargs )
        context["title"] = 'New Agent'
        context["savebtn"] = 'Add Agent'
        return context

    # used to update a supplier's info


class AgentUpdateView( SuccessMessageMixin, UpdateView ):
    model = Agent
    form_class = AgentForm
    success_url = '/transactions/agents'
    success_message = "Agent details has been updated successfully"
    template_name = "agents/edit_agents.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data( **kwargs )
        context["title"] = 'Edit Agents'
        context["savebtn"] = 'Save Changes'
        context["delbtn"] = 'Delete Agent'
        return context


# used to delete a supplier
class AgentDeleteView( View ):
    template_name = "agents/delete_agents.html"
    success_message = "Agent has been deleted successfully"

    def get(self, request, pk):
        agent = get_object_or_404( Agent, pk=pk )
        return render( request, self.template_name, {'object': agent} )

    def post(self, request, pk):
        agent = get_object_or_404( Agent, pk=pk )
        agent.is_deleted = True
        agent.save()
        messages.success( request, self.success_message )
        return redirect( 'agent-list' )


# used to view a supplier's profile
class AgentView( View ):
    def get(self, request, name):
        agentobj = get_object_or_404( Agent, name=name )
        sale_bill = SaleBill.objects.filter( agent=agentobj )
        page = request.GET.get( 'page', 1 )
        paginator = Paginator( sale_bill, 10 )
        try:
            sales = paginator.page( page )
        except PageNotAnInteger:
            sales = paginator.page( 1 )
        except EmptyPage:
            sales = paginator.page( paginator.num_pages )
        context = {
            'agent': agentobj,
            'bills': sales
        }
        return render( request, 'agents/agents.html', context )


# shows the list of bills of all purchases
class PurchaseView( ListView ):
    model = PurchaseBill
    template_name = "purchases/purchases_list.html"
    context_object_name = 'bills'
    ordering = ['-time']
    paginate_by = 10


# used to select the supplier
class SelectSupplierView( View ):
    form_class = SelectSupplierForm
    template_name = 'purchases/select_supplier.html'

    def get(self, request, *args, **kwargs):  # loads the form page
        form = self.form_class
        return render( request, self.template_name, {'form': form} )

    def post(self, request, *args, **kwargs):  # gets selected supplier and redirects to 'PurchaseCreateView' class
        form = self.form_class( request.POST )
        if form.is_valid():
            supplierid = request.POST.get( "supplier" )
            supplier = get_object_or_404( Supplier, id=supplierid )
            return redirect( 'new-purchase', supplier.pk )
        return render( request, self.template_name, {'form': form} )


# used to generate a bill object and save items
class PurchaseCreateView( View ):
    template_name = 'purchases/new_purchase.html'

    def get(self, request, pk):
        formset = PurchaseItemFormset( request.GET or None )  # renders an empty formset
        supplierobj = get_object_or_404( Supplier, pk=pk )  # gets the supplier object
        context = {

transactions/templates/sales/delete_sale.html
{% extends "base.html" %}


{% block title %} Delete Sale {% endblock title %}


{% block content %}
                
    <form method="post">
        
        {% csrf_token %}
        
        <fieldset class="form-group">
            <div style="color:#575757; font-style: bold; font-size: 3rem; border-bottom: 1px solid white;">Delete Sale Bill</div> <br>
            <h2 style="color:#575757;">Are you sure you want to delete the Sale Bill No: {{ object.billno }}?</h2>
        </fieldset>

        <div class="form-group">  
            <button type="submit" class="btn btn-danger">Yes, Delete</button>
            <a href="{% url 'sales-list' %}" class="btn btn-secondary">Cancel</a>
        </div>
        
    </form>

{% endblock content %}

transactions/templates/sales/new_sale.html
{% extends "base.html" %}
{% load static %}


{% block title %} New Purchase {% endblock title %}


{% block content %}

    <div style="color:#575757; font-style: bold; font-size: 3rem; border-bottom: 1px solid white;">New Sale</div>

        <br>

        <div class="panel panel-default">
            <div class="panel-heading panel-heading-text">Costumer Details</div>
            <div class="panel-body">

                <div class="form-group">
                    <label for="id_name" class="panel-body-text">Costumer Name:</label>
                    <input type="text" class="form-control textinput" id="id_name" value="{{ costumer.name }}" disabled>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="id_phone" class="panel-body-text">Phone No:</label>
                        <input type="text" class="form-control textinput" id="id_phone" value="{{ costumer.phone }}" disabled>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="id_nipt" class="panel-body-text">NIpt No:</label>
                        <input type="nipt" class="form-control textinput" id="id_nipt" value="{{ costumer.nipt }}" disabled>
                    </div>
                </div>

            </div>
        </div>

        <br>

        <form method="post" class="panel panel-default">

            {% csrf_token %}
            {{ formset.management_form }}

            <div class="panel-heading panel-heading-text">Product Details</div>

                <div id="stockitem">
                    <div class="panel-body">
                    {% for form in formset %}
                        <div class="row form-row">
                            <div class="form-group col-md-6">
                                {{ form.stock.errors }}
                                <label class="panel-body-text">Stock:</label>
                                {{ form.stock }}
                            </div>
                            <div class="form-group col-md-2">
                                <label class="panel-body-text">Price per item:</label>
                                {{ form.perprice }}
                            </div>
                            <div class="form-group col-md-2">
                                {{ form.quantity.errors }}
                                <label class="panel-body-text">Quantity:</label>
                                {{ form.quantity }}
                            </div>
                            <div class="form-group col-md-1">
                                <label class="panel-body-text">Price:</label>
                                <input type="text" class="textinput form-control totalprice" value="1" disabled required>
                            </div>
                            <div class="form-group col-md-1">
                                <label class="panel-body-text" style="color: #000">.</label>
                                <button class="form-control btn btn-danger remove-form-row">-</button>
                            </div>
                        </div>
                    {% endfor %}
                        <div style="text-align: right;">
                            <a href="#" class="add-form-row">+ Add More</a>
                        </div>
                    </div>
                </div>


            <br>

            <div class="align-middle">
                <button type="submit" class="btn btn-success">Add to Sales</button>
                <a href="{% url 'select-costumer' %}" class="btn btn-danger">Go Back</a>
                <a href="{% url 'sales-list' %}" class="btn btn-secondary">Cancel</a>
            </div>

        </form>

    </div>

    <!-- Custom JS to add and remove item forms -->
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/dialogbox.js' %}"></script>
    <script type="text/javascript">
       //creates custom alert object
        var custom_alert = new custom_alert();

        function updateElementIndex(el, prefix, ndx) {
            var id_regex = new RegExp('(' + prefix + '-\\d+)');
            var replacement = prefix + '-' + ndx;
            if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
            if (el.id) el.id = el.id.replace(id_regex, replacement);
            if (el.name) el.name = el.name.replace(id_regex, replacement);
        }

        //stores the total no of item forms
        var total = 1;

        function cloneMore(selector, prefix) {
            var newElement = $(selector).clone(true);
            //var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
            newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function() {
                var name = $(this).attr('name')
                if(name) {
                    name = name.replace('-' + (total-1) + '-', '-' + total + '-');
                    var id = 'id_' + name;
                    $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
                }
            });
            newElement.find('label').each(function() {
                var forValue = $(this).attr('for');
                if (forValue) {
                forValue = forValue.replace('-' + (total-1) + '-', '-' + total + '-');
                $(this).attr({'for': forValue});
                }
            });
            total++;
            $('#id_' + prefix + '-TOTAL_FORMS').val(total);
            $(selector).after(newElement);
            return false;
        }

        function deleteForm(prefix, btn) {
            //var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
            if (total > 1){
                btn.closest('.form-row').remove();
                var forms = $('.form-row');
                $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
                for (var i=0, formCount=forms.length; i<formCount; i++) {
                    $(forms.get(i)).find(':input').each(function() {
                        updateElementIndex(this, prefix, i);
                    });
                }
                total--;
            } else {
                custom_alert.render('Field cannot be deleted');
            }
            return false;
        }

        $(document).on('click', '.add-form-row', function(e){
            e.preventDefault();
            cloneMore('.form-row:last', 'form');
            return false;
        });

        $(document).on('click', '.remove-form-row', function(e){
            e.preventDefault();
            deleteForm('form', $(this));
            return false;
        });


        //stores pk and quantity of all stocks into a js object 'stocks'
        var stocks = [
            {% for stock in stocks %}
                {% if not forloop.first %},{% endif %}
                {
                    pk          : {{ stock.pk }},
                    quantity    : {{ stock.quantity }}
                }
            {% endfor %}
        ];

        //updates the total price by multiplying 'price per item' and 'quantity'
        $(document).on('change', '.setprice', function(e){
            e.preventDefault();
            //gets the values
            var element = $(this);
            var stock = element.parents('.form-row').find('.stock').val();
            var quantity = element.parents('.form-row').find('.quantity').val();
            var perprice = element.parents('.form-row').find('.price').val();
            //checks if stocks are available
            stocks.forEach(function(stockSummary, i) {
                var pk = stocks[i].pk;
                var squantity = stocks[i].quantity;
                if(stock == pk) {
                    //checks if ordered stock is more than available stock
                    if(quantity > squantity){
                        quantity = quantity - 1;
                        if(quantity <= 1){
                            //no stocks are available. Attempts to delete field
                            custom_alert.render('Stocks are currently unavailable. Field will be removed;');
                            //Sets quantity to 0 as failsafe for when the total no of item forms are 1
                            element.parents('.form-row').find('.quantity').val(0);
                            deleteForm('form', element);
                        } else {
                            element.parents('.form-row').find('.quantity').val(squantity-1);
                            quantity = squantity - 1;
                            custom_alert.render('Exceeded current stock available');
                        }
                    }
                }
            });
            //calculates the total
            var tprice = quantity * perprice;
            //sets it to field
            element.parents('.form-row').find('.totalprice').val(tprice);
            return false;
        });


</script>

{% endblock content %}

transactions/templates/sales/sales_list.html
{% extends "base.html" %}

{% load widget_tweaks %}


{% block title %} Sales List {% endblock title %}


{% block content %}
    
    <div class="row" style="color: #575757; font-style: bold; font-size: 3rem;">
        <div class="col-md-8">Sales List</div>
        <div class="col-md-4">               
            <div style="float:right;"> <a class="btn btn-success" href="{% url 'select-costumer' %}">New Outgoing Stock</a> </div>
        </div>
    </div>
    
    <br>

    <table class="table table-css table-bordered table-hover"> 
            
        <thead class="thead-dark align-middle">
            <tr>
                <th width="10%">Bill No.</th>
                <th width="15%">Customer</th>
                <th width="15%">Stocks Sold</th>
                <th width="10%">Quantity Sold</th>
                <th width="10%">Total Sold Price</th>
                <th width="15%">Date</th>
                <th width="25%">Actions</th>
            </tr>
        </thead>

{% if bills %}

        <tbody>
            {% for sale in bills %}
            <tr>
                <td class="align-middle"> <p>{{ sale.billno }}</p> </td>
                <td class=""> {{ sale.costumer }} <br> <small style="color: #909494">Ph No : {{ sale.costumer.phone }}</small> </td>
                <td class="align-middle">{% for item in sale.get_items_list %} {{ item.stock.name }} <br> {% endfor %}</td>
                <td class="align-middle">{% for item in sale.get_items_list %} {{ item.quantity }} <br> {% endfor %}</td>     
                <td class="align-middle">${{ sale.get_total_price }}</td>
                <td class="align-middle">{{ sale.time.date }}</td>
                <td class="align-middle"> <a href="{% url 'sale-bill' sale.billno %}" class="btn btn-secondary btn-sm">View Bill</a> <a href="{% url 'delete-sale' sale.pk %}" class="btn btn-danger btn-sm">Delete Bill</a> </td>
            </tr>
            {% endfor %}
        </tbody>

    </table>

    <div class="align-middle">
        {% if is_paginated %}

            {% if page_obj.has_previous %}
                <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}

        {% endif %}
    </div>

{% else %}

        <tbody></tbody>   
    </table>

    <br><br><br><br><br><br><br><br>
    <div style="color: #575757; font-style: bold; font-size: 1.5rem; text-align: center;">The records are empty. Please try adding some.</div>

{% endif %}

{% endblock content %}

transactions/templates/sales/select_customer.html
{% extends "base.html" %}


{% block title %} New Sale {% endblock title %}


{% block content %}

    <div style="color:#575757; font-style: bold; font-size: 3rem; border-bottom: 1px solid white;">New Sale</div>
    
    <br>
    
    <form method="post">

        {% csrf_token %}
        
        {% for field in form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %}

        <br>
        <div class="align-middle">
            <button type="submit" class="btn btn-success">Next</button>
            <a href="{% url 'sales-list' %}" class="btn btn-secondary">Cancel</a>
        </div>
        
    </form>

{% endblock content %}